#!/usr/bin/env python3

import pyttsx3
import os

engine = pyttsx3.init()
engine.setProperty("rate", 150)
    
def main():
    while True:
        text = input("> ")
        print("Speaking.")
        engine.say(text)
        engine.runAndWait()
        print("Done.")
    

if __name__ == "__main__":
    print("Welcome to text to speech.\n\n")
    main()
